# Site settings
title: Alex - Senior Data Scientist
description: Welcome to my personal page! I am Alex, a senior data scientist with over 10 years of experience in data analysis, machine learning, and statistical modeling.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alext90.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: dark

# Defaults for all collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alex"

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Social media links (optional)
github_username: alext90
#linkedin_username: yourlinkedinprofile

# Google Analytics (optional)
#google_analytics: UA-XXXXXXXX-X

# Exclude from processing
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"

# Include specific files
include:
  - "_pages"

# Markdown configuration
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
